### ISSUE TITLE
关于2024华东杯A题的代码的问题

### ISSUE THREAD

**Issue by Re8953** [BiologyHazard/hdmcm2024A#1]
你好，我想请教一下你2024华东杯A题的解题思路，以及想要参考一下你们做题的论文，谢谢大家啦~

**Comment by BiologyHazard** [comment]
您好，论文恕不公开，非常抱歉。

**Comment by Re8953** [comment]
好的，麻烦你了，另外我还想问一下，您在使用蒙特卡洛法求解第三问的时候得出了胜率的矩阵之后是怎么判断是否有平衡点的，如果有是通过什么方法找到的

**Comment by BiologyHazard** [comment]
见
https://github.com/BiologyHazard/hdmcm2024A/blob/main/problem_3_1.py

**Comment by Re8953** [comment]
好的，谢谢你！！！！
